### ISSUE TITLE
Añadir procedimiento de Code Review

### ISSUE THREAD

**Issue by sebasmagri** [mozillahispano/dev-docs#9]
Añadir un procedimiento a la sección de Git, o en una nueva sección, para detallar el proceso de revisión de Pull Requests y su aprobación para merge.

**Comment by sebasmagri** [comment]
Ping @fjaguero @nukeador @stripTM @ccarruitero 

La idea es esbozar un procedimiento para code reviews que se pueda implementar en todos los proyectos. Algo sencillo, lo menos burocrático posible, pero que nos permita formalizar de cierta manera los requerimientos para mezclar un pull request.

**Comment by fjaguero** [comment]
También tener en cuenta los tiempos y qué hacer cuando X pull request no ha sido merged todavia

**Comment by sebasmagri** [comment]
Algunas referencias que podemos tomar y adaptar a nuestras herramientas:

https://wiki.openstack.org/wiki/GerritJenkinsGit
https://wiki.documentfoundation.org/Development/GitReview
https://developer.mozilla.org/en-US/docs/Code_Review_FAQ

**Comment by stripTM** [comment]
Supongo que para estos desarrollos descentralizados es lo que que toca, durante estas jornadas se han identificado aun montón de tareas
https://intranet.mozilla-hispano.org/projects/work-week-2014/task_lists

Y creo que en esta https://intranet.mozilla-hispano.org/projects/work-week-2014/tasks/1086 es posiblemente la que más se ajusta para que incorporemos esto que comentáis.

**Comment by fjaguero** [comment]
@stripTM @sebasmagri Veo que en la tarea de la intranet se refiere al README. En ese caso yo haría del README un index de la web de dev-docs, enviándo a los usuarios ahí (y así evitar un README infinito). ¿Cómo lo ven?

**Comment by sebasmagri** [comment]
On 21/04 11:57, Fernando Agüero wrote:

> @stripTM @sebasmagri Veo que en la tarea de la intranet se refiere al README.
> En ese caso yo haría del README un index de la web de dev-docs, enviándo a los
> usuarios ahí (y así evitar un README infinito). ¿Cómo lo ven?
> 
> —
> Reply to this email directly or view it on GitHub.*

@fjaguero para mi, mientras menos pesado el README mejor. Si desde ahí podemos
enlazar a recursos en otro sitio como al de dev-docs en RTFD o a un archivo
CONTRIBUTING, que es el estándar que sugiere GitHub, mucho mejor.

## 

Sebastián Ramírez Magrí [sebasmagri]

**Comment by fjaguero** [comment]
@sebasmagri @stripTM Entonces yo limpiaria el README, dejando una explicación más sencilla y enlzando a dev-docs (documentación) y a un CONTRIBUTING (líneas generales de cómo colaborar). ¿Cómo lo ven?

**Comment by sebasmagri** [comment]
On 21/04 12:10, Fernando Agüero wrote:

> @sebasmagri @stripTM Entonces yo limpiaria el README, dejando una explicación
> más sencilla y enlzando a dev-docs (documentación) y a un CONTRIBUTING (líneas
> generales de cómo colaborar). ¿Cómo lo ven?
> 
> —
> Reply to this email directly or view it on GitHub.*

Me parece bien @fjaguero...

También estoy pensando en que estos lineamientos que están saliendo deberían
documentarse igual. Habría que crear un capítulo para lineamientos generales
para documentación de los proyectos.

Saludos.

## 

Sebastián Ramírez Magrí [sebasmagri]

**Comment by fjaguero** [comment]
BTW, no es que sea offtopic, pero estoy viendo que en el grupo de MH estamos escribiendo en español y en ingés. Habrá que definir eso también.

**Comment by sebasmagri** [comment]
On 21/04 13:45, Fernando Agüero wrote:

> BTW, no es que sea offtopic, pero estoy viendo que en el grupo de MH estamos
> escribiendo en español y en ingés. Habrá que definir eso también.
> 
> —
> Reply to this email directly or view it on GitHub.*

Si, es una duda que he tenido antes sobre todo con los commits. Es bueno
discutirlo y dejarlo documentado.

## 

Sebastián Ramírez Magrí [sebasmagri]

**Comment by fjaguero** [comment]
@stripTM @sebasmagri ¿Les parece que abramos un thread en la lista de correos de Labs para comentar todo esto, junto a un Pad para ir organizando el README, CONTRIBUTING, etc?

**Comment by sebasmagri** [comment]
On 21/04 15:27, Fernando Agüero wrote:

> @stripTM @sebasmagri ¿Les parece que abramos un thread en la lista de correos
> de Labs para comentar todo esto, junto a un Pad para ir organizando el README,
> CONTRIBUTING, etc?
> 
> —
> Reply to this email directly or view it on GitHub.*

+1

## 

Sebastián Ramírez Magrí [sebasmagri]

**Comment by iampbernardo** [comment]
Perfecto.

Pablo Bernardo

Desarrollador | Software Libre

email : voylinux@gmail.com
twitter: @voylinux https://www.twitter.com/voylinux
github: https://github.com/voylinux

**Comment by fjaguero** [comment]
Ya mandé un mail para ir comentándolo ahí.

**Comment by fjaguero** [comment]
Voy a mover esta conversación a un issue nuevo en esta repo, es mucho más fácil seguirla que por la lista o un etherpad (podemos adjuntar el etherpad al issue).

**Comment by fjaguero** [comment]
Lo cierro para seguirlo en el #10. Lo tengo asignado para hacer followup de la revisión.

**Comment by sebasmagri** [comment]
Hello, 

Sebastián Magrí has invited you to join them on Peerio! Their Peerio username is sebasmagri. 

Peerio is a secure messaging, file sharing, and cloud storage app that is free and easy to use. This invitation will give you 250MB of bonus storage when you join Peerio with the e-mail address you received this message at. You can get the app and learn more at www.peerio.com.

## 

The Peerio Team

Don't want to receive invitations to join Peerio? Click here to unsubscribe.=
